### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Bretra** [643824979/LLNavgationBar#1]
![image](https://user-images.githubusercontent.com/12798195/49981847-ebbbdb80-ff94-11e8-8a6f-2a9f709d6a40.png)
![image](https://user-images.githubusercontent.com/12798195/49981854-f24a5300-ff94-11e8-847c-e8fbf42f40a5.png)

老铁，bug，视图没有添加到父视图就进行约束布局会造成崩溃的

**Comment by Bretra** [comment]
![d6bab0e3-57f1-404a-a531-5d209c2cfad9](https://user-images.githubusercontent.com/12798195/49981951-5a009e00-ff95-11e8-954e-4cbd0720f1e9.png)

**Comment by longlz19** [comment]
已修复
